### ISSUE TITLE
Move known issues from readme to issues.

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/bom-base#37]
# Current situation
There's a list of known issues in the readme.

- [x] Retry failed harvesting attempts (e.g. when source offline)
- [ ] #40
- [ ] #41
- [ ] #42
- [ ] #43
- [x] #44
- [ ] #45
- [ ] #46
- [ ] #48
- [ ] #47
- [ ] #49

# Proposed Situation
Move the known issues from the readme to issues to make them more contributor friendly to resolve

# Extra
It more easy to see who's working on what.

**Comment by JeroenKnoops** [comment]
The label documentation is confusing... I remove it.

**Comment by Brend-Smits** [comment]
- [ ] Retry failed harvesting attempts (e.g. when source offline)
- [ ]  Handle false information (e.g. non-existing source location)
- [ ]  Harvesting metadata from inner source repositories
- [ ]  Add auto-converter for obvious (but formally wrong) SPDX license names
- [ ]  Add harvester for Maven
- [ ]  Add harvester for NPM
- [ ]  Add harvester for APK
- [ ]  Add harvester for Debian
- [ ]  Add harvester for NuGet
- [ ]  Add harvester for Cargo
- [ ]  Persist metadata in database

**Comment by timovandeput** [comment]
Removed the "to do" items from README in #53 .
